Entity/Top.php
<?php

namespace XLabs\TopSetBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use XLabs\TopSetBundle\Entity\Entry;
use Doctrine\Common\Collections\ArrayCollection;
use XLabs\ResultCacheBundle\Annotations as XLabsResultCache;

/**
 * @ORM\Entity
 * @ORM\Table(name="xltsb_topsets")
 * @XLabsResultCache\Clear(onFlush={}, {
 *      @XLabsResultCache\Key(onFlush={"update", "delete"}, type="literal", method="getXLabsResultCacheKeyForItem"),
 *      @XLabsResultCache\Key(onFlush={"insert", "update", "delete"}, type="prefix", method="getXLabsResultCacheKeyForCollection")
 * })
 */
class Top
{
    const RESULT_CACHE_ITEM_PREFIX = 'mm_topset_';
    //const RESULT_CACHE_ITEM_TTL = 604800; // 1 week
    const RESULT_CACHE_ITEM_TTL = 86400; // 24h
    const RESULT_CACHE_COLLECTION_PREFIX = 'mm_topsets_';
    const RESULT_CACHE_COLLECTION_TTL = 3600;

    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @ORM\Column(name="title", type="string", length=255, nullable=true)
     */
    private $title;

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @ORM\Column(name="entity_fqcn", type="string", length=255, nullable=false)
     */
    private $entity_fqcn;

    public function getEntityFQCN()
    {
        return $this->entity_fqcn;
    }

    public function setEntityFQCN($entity_fqcn)
    {
        $this->entity_fqcn = $entity_fqcn;
    }

    /**
     * @ORM\OneToMany(targetEntity="XLabs\TopSetBundle\Entity\Entry", mappedBy="top", cascade={"persist", "remove"})
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private $entries;

    public function getEntries()
    {
        return $this->entries;
    }

    public function addEntry(Entry $entry)
    {
        $this->entries->add($entry);
        $entry->setTop($this);
    }

    public function removeEntry(Entry$entry)
    {
        $this->entries->removeElement($entry);
    }

    public function __construct()
    {
        $this->entries = new ArrayCollection();
    }

    public function getXLabsResultCacheKeyForItem()
    {
        return $this::RESULT_CACHE_ITEM_PREFIX.$this->getId();
    }

    public function getXLabsResultCacheKeyForCollection()
    {
        return $this::RESULT_CACHE_COLLECTION_PREFIX;
    }
}

Form/TopType.php
<?php

namespace XLabs\TopSetBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use XLabs\TopSetBundle\Entity\Top;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

use Doctrine\Common\Annotations\AnnotationReader;
use XLabs\TopSetBundle\Annotations\Config as XLabsTopSetConfig;

class TopType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',TextType::class, array(
                'required' => true,
                'attr' => array(
                    'style' => 'width: 300px;',
                    'maxlength' => '255'
                )
            ))
            ;

        $factory = $builder->getFormFactory();
        $em = $options['entity_manager'];
        $builder->addEventListener(FormEvents::PRE_SET_DATA, function(FormEvent $event) use($factory, $em){
            $form = $event->getForm();
            $top = $event->getData();

            // Allow only to change entityType when creating it
            if(!$top || !$top->getId())
            {
                $entities = array(
                    '' => 'Select one ...'
                );
                $meta = $em->getMetadataFactory()->getAllMetadata();
                $reader = new AnnotationReader();
                foreach($meta as $m)
                {
                    $entity = $m->getName();
                    $ref = new \ReflectionClass($entity);
                    $XLabsTopSetAnnotation = $reader->getClassAnnotation($ref, XLabsTopSetConfig::$annotationName);
                    if($XLabsTopSetAnnotation && property_exists($XLabsTopSetAnnotation, 'routeJSON'))
                    {
                        $entities[$m->getName()] = $ref->getShortName().' ('.$m->getName().')';
                    }
                }

                $form->add('entity_fqcn', ChoiceType::class,array(
                    'required' => true,
                    'choices' => array_flip($entities)
                ));
            }
        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Top::class,
        ));
        $resolver->setRequired('entity_manager');
    }

    public function getBlockPrefix()
    {
        return 'xlabs_topset_bundle_top_type';
    }
}

Controller/TopController.php
<?php

namespace XLabs\TopSetBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use XLabs\TopSetBundle\Entity\Top;
use XLabs\TopSetBundle\Form\TopType;
use XLabs\TopSetBundle\Form\TopEntriesType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\DBALException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class TopController extends Controller
{
    public function managerAction()
    {
        $em = $this->getDoctrine()->getManager();
        $top_sets = $em->getRepository('XLabsTopSetBundle:Top')->findAll();

        return $this->render('XLabsTopSetBundle:Top:manager.html.twig', array(
            'top_sets' => $top_sets
        ));
    }

    public function formAction($top_id)
    {
        $request = $this->get('request_stack')->getCurrentRequest();
        $em = $this->getDoctrine()->getManager();

        $top = $top_id ? $em->getRepository('XLabsTopSetBundle:Top')->findOneBy(array(
            'id' => $top_id
        )) : new Top();
        $form = $this->createForm(TopType::class, $top, array(
            'entity_manager' => $em
        ));

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $em->persist($top);
            $em->flush();

            return $this->render('XLabsTopSetBundle::fancybox_close.html.twig');
        }

        $response = $this->render('XLabsTopSetBundle:Top:form.html.twig', array(
            'top' => $top,
            'form' => $form->createView()
        ));
        return $response;
    }

    public function deleteAction($top_id)
    {
        $request = $this->get('request_stack')->getCurrentRequest();
        $em = $this->getDoctrine()->getManager();

        $top = $em->getRepository('XLabsTopSetBundle:Top')->findOneBy(array(
            'id' => $top_id
        ));

        try {
            $em->remove($top);
            $em->flush();
        } catch(DBALException $e) {
            $this->get('session')->getFlashBag()->add('mm_top_error', $e->getMessage());
        }

        return $this->redirect($this->generateUrl('xlabs_topset_manager'));
    }

    public function entriesAction($top_id)
    {
        $request = $this->get('request_stack')->getCurrentRequest();
        $em = $this->getDoctrine()->getManager();

        $top = $em->getRepository('XLabsTopSetBundle:Top')->findOneBy(array(
            'id' => $top_id
        ));

        // Original collection handler
        $original_entries = new ArrayCollection();
        foreach($top->getEntries() as $item)
        {
            $original_entries->add($item);
        }

        // Read annotation in Entity to get the JSON list
        $entry_manager = $this->get('xlabs_topset_entry_manager');
        $json_list = $entry_manager->getEntriesJSON($top->getEntityFQCN());

        if(is_null($json_list))
        {
            throw new NotFoundHttpException('You need to create annotation in "'.$top->getEntityFQCN().'" entity for the JSON list:  @XLabsTopSet\Config(routeJSON="<your_routing_id>")');
        }

        $form = $this->createForm(TopEntriesType::class, $top, array(
            'json_list' => $json_list
        ));

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            try {
                // Collection handler
                foreach($original_entries as $item)
                {
                    if(!$top->getEntries()->contains($item))
                    {
                        $em->remove($item);
                    }
                }

                $em->persist($top);
                $em->flush();
                return $this->render('MMCoreBundle::fancybox_close.html.twig');
            } catch(DBALException $e) {
                $this->get('session')->getFlashBag()->add('mm_top_error', $e->getMessage());
            }

            return $this->render('XLabsTopSetBundle::fancybox_close.html.twig');
        }

        $response = $this->render('XLabsTopSetBundle:Top:entries.html.twig', array(
            'top' => $top,
            'form' => $form->createView(),
            'json_list' => $json_list
        ));
        return $response;
    }

    public function usageAction($top_id)
    {
        $em = $this->getDoctrine()->getManager();
        $top = $em->getRepository('XLabsTopSetBundle:Top')->findOneBy(array(
            'id' => $top_id
        ));
        return $this->render('XLabsTopSetBundle:Top:usage.html.twig', array(
            'top' => $top
        ));
    }
}

Resources/views/Top/entries.html.twig
{% extends 'XLabsTopSetBundle::base_fancybox_form.html.twig' %}

{# COLLECTION HANDLER #}
{% form_theme form _self %}
{% block _xlabs_topset_bundle_top_type_entries_widget %}
    <script src="{{ asset('bundles/xlabstopset/js/daterange/moment.min.js') }}"></script>
    <script src="{{ asset('bundles/xlabstopset/js/daterange/jquery.daterangepicker.min.js') }}"></script>
    <link href="{{ asset('bundles/xlabstopset/js/daterange/daterangepicker.min.css') }}" rel="stylesheet">

    {# Empty entry item #}
    {% include 'XLabsTopSetBundle:Entry/item:entry.html.twig' %}

    {# Empty search result item #}
    {% include 'XLabsTopSetBundle:Top/search:search_results_item.html.twig' %}

    {{ form_widget(form) }}
{% endblock %}
{% block _xlabs_topset_bundle_top_type_entries_entry_row %}
    <div class="collection-item item">
        {% include 'XLabsTopSetBundle:Entry:form.html.twig' with {
            'form': form
        } %}
    </div>
    <div style="float: none; clear: both;"></div>
{% endblock %}

{% block headingJS %}
    {{ parent() }}
    <script src="{{ asset('bundles/xlabstopset/js/collection_handler.js') }}"></script>
    <script src="{{ asset('bundles/xlabstopset/js/jquery.preloader/jquery.preloader.js') }}"></script>
    <script src="{{ asset('bundles/xlabstopset/js/functions.js') }}"></script>

    <script type="text/javascript">
        let json_list = JSON.parse('{{ json_list | raw | e('js') }}');

        function checkNoEntries()
        {
            // Show "no entries" label
            if(!$('#{{ form.vars.id }}_entries .collection-item').length)
            {
                $('#no_entries_selected').show();
            } else {
                $('#no_entries_selected').hide();
            }
        }

        let selected_search_result = false;
        $(document).ready(function(){
            new COLLECTION_HANDLER('#{{ form.vars.id }}_entries')
                .setCallback('onAdd', function(elem){
                    // a search result is clicked
                    let current_collection_item = elem.find('div.collection-item');
                    let position = parseInt(current_collection_item.index('.collection-item')) + 1;

                    // Fill in form
                    current_collection_item.find('input[id*="{{ form.vars.id }}_entries_"]').filter(function(){
                        return $(this).attr('id').match(/_object_id$/);
                    }).val(selected_search_result.id);
                    current_collection_item.find('input[id*="{{ form.vars.id }}_entries_"]').filter(function(){
                        return $(this).attr('id').match(/_position$/);
                    }).val(position);

                    let entry_data = {
                        id: selected_search_result.id,
                        title: selected_search_result.title,
                        image: selected_search_result.image,
                        position: position,
                        startdate: false,
                        enddate: false
                    };
                    addEntryItem(current_collection_item, entry_data);

                    selected_search_result = false; // reset selected search result
                    checkNoEntries();
                })
                .setCallback('onRemove', function(elem){
                    $('#sortable_entries').sortable('refresh');
                    $('#sortable_entries').sortable('refreshPositions');
                    let position = 1;
                    $.each($('#sortable_entries').find('div.collection-item').not(elem.get(0)), function(){
                        $(this).find('input[id*="{{ form.vars.id }}_entries_"]').filter(function(){
                            return $(this).attr('id').match(/_position$/);
                        }).val(position);
                        $(this).find('.entry_item .entry_item_position').text(position);
                        position++
                    });
                    checkNoEntries();
                })
                .setAddButtonText('Add new entry');

            $('#sortable_entries').sortable({
                //connectWith: '.connectedSortable',
                items: 'div.collection-item',
                placeholder: 'ui-state-highlight',
                cursor: 'pointer',
                helper: 'original',
                revert: 0,
                zIndex: 9999,
                scroll: false,
                start: function(e, ui) {
                    ui.item.addClass('ui-state-highlight');
                },
                stop: function(e, ui){
                    ui.item.removeClass('ui-state-highlight');
                    let container = $(this);
                    $.each(container.find('div.collection-item'), function(){
                        let position = parseInt($(this).closest('.collection-item').index('.collection-item')) + 1;
                        $(this).find('.entry_item_position').text(position);
                        $(this).find('input[id*="{{ form.vars.id }}_entries_"]').filter(function(){
                            return $(this).attr('id').match(/_position$/);
                        }).val(position);
                    });
                },
                receive: function(e, ui){},
                over: function (event, ui) {},
                out: function (event, ui) {},
                create: function (event, ui) {
                    //updateTotals();
                }
            }).disableSelection();

            $('#search_results').on('click', '.search_result_item', function(e){
                e.stopPropagation();
                let item = $(this);
                selected_search_result = {
                    id: item.find('.search_result_item_id').text(),
                    title: item.find('.search_result_item_title').text(),
                    image: item.find('.search_result_item_image').text() ? item.find('.search_result_item_image').text() : '',
                };
                // check if element already in top
                let existingEntry = false;
                $.each($('#sortable_entries').find('div.collection-item'), function(){
                    let entry_obj_id_input = $(this).find('input[id*="{{ form.vars.id }}_entries_"]').filter(function(){
                        return $(this).attr('id').match(/_object_id$/);
                    });
                    if(entry_obj_id_input.val() == selected_search_result.id)
                    {
                        existingEntry = entry_obj_id_input.closest('div.collection-item');
                    }
                });

                if(existingEntry)
                {
                    // blink entry
                    existingEntry.addClass('existing_entry');
                    setTimeout(function(){
                        existingEntry.removeClass('existing_entry');
                    }, 2000);
                } else {
                    $('.add-collection-item').trigger('click');
                }
            });
            $('#search_results').on('click', '.add_search_result', function(e){
                e.stopPropagation();
                $(this).closest('.search_result_item').trigger('click');
            });

            // Hide ADD button from collection_handler.js
            $('.add-collection-item-c').hide();

            // Show message when no entries set
            checkNoEntries();

            // Unfold date range selector on span click
            $('body').on('click', '.entry_item_date_range', function(e){
                e.stopPropagation();
                $(this).closest('.collection-item').find('.dateRange_selection').data('dateRangePicker').open();
            });
        });
    </script>
{% endblock headingJS %}

{% block content %}
    {% set form_title = 'Manage entries' %}
    <h2 class="page_title">
        <br />{{ form_title }}
    </h2>

    {% if app.session.flashBag.has('mm_top_error') %}
        <div>
            {% for msg in app.session.flashBag.get('mm_top_error') %}
                <p>{{ msg }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <div class="wrapper">
        {# Current entries #}
        <div class="left">
            {% set formAction = path('xlabs_topset_form_entries', { 'top_id': top.id }) %}
            <div class="loader" style="display:none;width: 100%;height: 100%;position: absolute;background: rgba(0, 0, 0, 0.32);z-index: 9;">
                <img src="{{ asset('bundles/xlabstopset/images/loader.png') }}" style="position: absolute;top: 40%;left: 45%;">
            </div>
            <div class="clear"></div>
            <form action="{{ formAction }}" method="post" enctype="multipart/form-data" id="top_entries_form" name="top_entries_form">
                <fieldset>
                    <legend>Entries</legend>
                    <div id="sortable_entries" class="">
                        {{ form_widget(form.entries) }}
                        <span id="no_entries_selected" style="display: none; font-size: .8em; color: #aaaaaa;">No entries selected yet</span>
                    </div>
                </fieldset>
                <div class="clear"></div>

                {{ form_rest(form) }}

                <div class="clear" style="height: 25px;"></div>
                <button type="submit" class="button">Save</button>
                <button type="button" id="close" class="button red">Close</button>
            </form>
        </div>

        {# Search to add more entries #}
        <div class="right">
            <form id="search_entries" name="search_entries" enctype="multipart/form-data">
                <input type="text" id="search_terms" name="search_terms" style="padding: 5px; border: 1px solid #dddddd; border-radius: 4px; color: #999999; -moz-box-shadow: 3px 3px 0px #EAF3F3; -webkit-box-shadow: 3px 3px 0px #EAF3F3; box-shadow: 3px 3px 0px #EAF3F3; margin-right: 5px;" />
                <button type="submit" id="search_but" class="button">Search {{ getTopFQCN(top) }}</button>
            </form>
            <div id="search_results"></div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}
    <script>
        $(document).ready(function(){
            $('form#search_entries').submit(function(e){
                e.preventDefault();
                $('#search_results').html('');
                let search_terms = $('#search_terms').val();
                let min_search_characters = 3;
                if(search_terms != '' && search_terms.length >= min_search_characters)
                {
                    $('.search_results_info.search_results_requirements').hide();
                    $('#search_results').preloader({
                        'loading_animation' : '/bundles/xlabstopset/js/jquery.preloader/preloader.png',
                        'loading_text': 'Live search, be patient :)'
                    }).preloader('enable');
                    let results = searchByIdOrTitle(search_terms);
                    if(results.length)
                    {
                        let results_items = '';
                        for(let i=0; i<results.length; i++)
                        {
                            let id = results[i];
                            let search_result_data = getEntryById(id);
                            search_result_data = {
                                id: search_result_data.id,
                                title: search_result_data.title,
                                image: search_result_data.image,
                            };
                            let item_html = getSearchResultItem(search_result_data);
                            results_items += item_html;
                        }
                        $('#search_results').html(results_items);
                        //$('#search_terms').val('');
                    } else {
                        $('#search_results').html('<span class="search_results_info">No results found</span>');
                    }
                    $('#search_results').preloader('disable');
                } else {
                    $('#search_results').html($('<span class="search_results_info search_results_requirements">At least ' + min_search_characters + ' characters required</span>'));
                    $('input#search_terms').focus();
                }
                return false;
            });

            $('button#close').on('click', function(e){
                e.preventDefault();
                parent.$.fancybox.close();
            });
        });
    </script>
{% endblock javascripts %}

Resources/views/Top/form.html.twig
{% extends 'XLabsTopSetBundle::base_fancybox_form.html.twig' %}

{% block headingJS %}{% endblock headingJS %}

{% block mm_xlabs_mmadmin %}{% endblock mm_xlabs_mmadmin %}

{% block content %}
    <style>
        .hidden-field {display: none;}
        .loader {display:none; width: 100%; height: 100%; position: absolute; background: rgba(0, 0, 0, 0.32); z-index: 9;}
        .loader img {position: absolute; top: 40%; left: 45%;}
    </style>

    <div class="xlabs_topset_bundle_wrapper">
        {% set form_title = top.id ? 'Edit Top' : 'Create Top' %}
        <h2 class="page_title">{{ form_title }}</h2>

        <div class="loader" style="">
            <img src="{{ asset('bundles/mmmedia/images/loader.png') }}">
        </div>

        {% set form_action = top.id ? path('xlabs_topset_form', { 'top_id': top.id }) : path('xlabs_topset_form') %}
        <form action="{{ form_action }}" method="post" enctype="multipart/form-data" id="top_form" name="top_form">
            <fieldset>
                <legend>Descriptive title</legend>
                {{ form_widget(form.title) }}
            </fieldset>

            {% if form.entity_fqcn is defined %}
                <fieldset>
                    <legend>Entity</legend>
                    {{ form_widget(form.entity_fqcn) }}
                </fieldset>
            {% else %}
                <span>{{ top.entityFQCN }}</span>
            {% endif %}

            {{ form_rest(form) }}

            {#<input type="submit" id="btnSubmit" class="but" value="Upload">#}
            <div style="margin-top: 20px;">
                <button type="submit" class="button">Save</button>
            </div>
        </form>
    </div>

    <script>
        $(document).ready(function(){
            $("input:text:visible:first").focus();
            });

            $('#top_form').submit(function(e){
                $('.loader').show();
                return true;
            });
        });
    </script>
{% endblock content %}

Resources/views/Top/manager.html.twig
{% extends 'XLabsTopSetBundle:Frontend:bundle_wrapper.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        ul.list {list-style-type: none; width: 500px; margin: 0 auto;}
        ul.list li {height: 50px; border: 1px solid #CEE7FC; border-radius: 4px; padding: 10px; overflow: hidden; margin: 7px 0;-moz-box-shadow: 4px 4px 0px #EAF3F3; -webkit-box-shadow: 4px 4px 0px #EAF3F3; box-shadow: 4px 4px 0px #EAF3F3;}
        ul.list li > *{float: left; line-height: 50px; margin: 0 3px;}
        ul.list li > a{float: right; text-decoration: none; color: #97D0F5; margin: 0 10px;}
        ul.list li > a:hover{text-decoration: underline;}
    </style>
{% endblock stylesheets %}

{% block headingJS %}
    <script type="text/javascript">
        $(document).ready(function(){
            // Popups
            $(".fancybox_iframe").fancybox({
                type: 'iframe',
                width: 1200,
                height: 450,
                closeBtn:'<a title="Close" class="fancybox-item fancybox-close" href="javascript:;"></a>',
                afterClose: function(){
                    parent.location.reload();
                }
            });
            $(".fancybox_iframe_no_reload").fancybox({
                type: 'iframe',
                width: 1200,
                height: 450,
                closeBtn:'<a title="Close" class="fancybox-item fancybox-close" href="javascript:;"></a>'
            });

            $('.delete').on('click', function(e){
                e.preventDefault();
                if(confirm('Are you sure you want to delete this top?'))
                {
                    location.href = $(this).attr('href');
                }
            })
        });
    </script>
{% endblock headingJS %}

{% block body %}
    <h2 class="page_title">
        <br />Top Manager
    </h2>

    {% if app.session.flashBag.has('mm_top_error') %}
        <div class="">
            {% for msg in app.session.flashBag.get('mm_top_error') %}
                <h2 class="" style=""> {{ msg }}</h2>
            {% endfor %}
        </div>
    {% endif %}

    <div class="wrapper">
        {# HREF is set in the button for fancybox (workaround) #}
        <button type="button" class="button fancybox_iframe" href="{{ path('xlabs_topset_form') }}">Create top</button>
        <div class="center">
            <ul class="list">
                {% for top in top_sets %}
                    {% include 'XLabsTopSetBundle:Top/item:top.html.twig' with {
                        'top': top
                    } %}
                {% else %}
                    <span style="display: block; font-size: .8em; color: #aaaaaa;">No top sets found</span>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock body %}

Resources/views/Top/usage.html.twig
{% extends 'XLabsTopSetBundle::base_fancybox_form.html.twig' %}

{% block content %}
    <h2 class="page_title">
        <br />USAGE
    </h2>
    <br />
    <div class="wrapper" style="min-height: 200px;">
        <div style="font-size: .8em;">
            From TWIG, you can get the object IDs collection by calling the following function:<br /><br />
            <span style="background: #cccccc; padding: 4px 12px; width: 100%; line-height: 2em;">getTopEntries({{ top.id }})</span>
            <br /><br /><br />
            You can achieve the same results from a controller by using the following service from the container:<br /><br />
            <span style="background: #cccccc; padding: 4px 12px; width: 100%; line-height: 2em;">$container->get('xlabs_topset_manager')->getTopEntries({{ top.id }});</span>
        </div>
        <br /><br /><br />
        <button type="button" id="close" class="button red">Close</button>
    </div>
{% endblock content %}

{% block javascripts %}
    <script>
        $(document).ready(function(){
            $('button#close').on('click', function(e){
                e.preventDefault();
                parent.$.fancybox.close();
            });
        });
    </script>
{% endblock javascripts %}